-- Create the acconti table for tracking employee advances
create table if not exists acconti (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  dipendente_id bigint references dipendenti(id) on delete cascade,
  data date not null default current_date,
  importo numeric not null default 0,
  note text
);

-- Enable RLS (Row Level Security) if you are using it (optional, but good practice)
alter table acconti enable row level security;

-- Allow public access (adjust based on your security policies)
create policy "Allow public access to acconti"
on acconti for all
using (true)
with check (true);
